### ISSUE TITLE
Выдает ошибку.Gives an error message.

### ISSUE THREAD

**Issue by kyprijan** [woxcab/rss_editor#1]
Загрузил на хостинг открываю, выдает ошибку.
Gives an error message.
[http://rssfeeder.96.lt/rss_editor-master/]
![default](https://cloud.githubusercontent.com/assets/20686304/17182963/3dd2e0fe-542e-11e6-93d1-04c3dabaa9f5.png)

**Comment by woxcab** [comment]
Добрый день.
Был ли передан get-параметр url?
В случае ошибок, отлавливаемых в скрипте, выдается страница с http-статусом 502 и посредством die сообщением ошибки (т.е. выдается страница, исходный код которой — чистый текст ошибки без любого HTML/XML форматирования).
Пример из описания README выдает корректный результат:
http://rssfeeder.96.lt/rss_editor-master/?url=http%3A%2F%2Fmilknews.ru%2Findex%2Fnovosti-moloko.rss&amp&add_namespace=xmlns%3Ayandex%3D%22http%3A%2F%2Fnews.yandex.ru%2F%22&remove=description&rename_from=full-text&rename_to=description&cdata[]=title&cdata[]=description&break=description

**Comment by kyprijan** [comment]
Понял, туплю так как php не знаю. А можете добавить такое, например в description есть символ "№" и его нужно заменить на "#".

**Comment by woxcab** [comment]
https://github.com/woxcab/rss_editor/commit/d895a646a16b30e25cce18feedd8bd67bc20017e 
Добавлена возможность замены не только вида "найти точное совпадение и заменить на такое", но и  используя любые другие регулярные выражения в формате PCRE. Также обновлён README с кратким описанием новых параметрво (приоритет 9) и в примере показан самый простой способ их применения как при обычной замене текста.
Т.е. в вашем случае паарметры могут быть, например, такими:

```
rss_editor-master/?url=some_encoded_url&replace_from=№&replace_to=%23&replace_in=description
```

что приведет к тому, что во всех `description` будут заменены все вхождения символа `№` на `#` (`%23` — его код, чтобы символ не воспринимался как составной элемент URL).

**Comment by kyprijan** [comment]
Привет. Не работает, ни из примера ни моё.
http://rssfeeder.96.lt/rss_editor-master/index.php?url=http%3A%2F%2Fmilknews.ru%2Findex%2Fnovosti-moloko.rss&amp&add_namespace=xmlns%3Ayandex%3D%22http%3A%2F%2Fnews.yandex.ru%2F%22&remove=description&rename_from=full-text&rename_to=description&cdata[]=title&cdata[]=description&break=description&replace_from=ё&replace_to=е&replace_in=description

http://rssfeeder.96.lt/rss_editor-master/index.php?url=https%3A%2F%2Fzapier.com%2Fengine%2frss%2f1176719%2fplane34%2f&replace_from=№&replace_to=%23&replace_in=description
![33333](https://cloud.githubusercontent.com/assets/20686304/17210430/9af568f4-54cb-11e6-8fd0-b87fc4e114fe.png)

**Comment by woxcab** [comment]
Теперь вроде работает нормально, в т.ч. на Вашем примере.

**Comment by kyprijan** [comment]
Спасибо тебе большое, давно искал.

**Comment by kyprijan** [comment]
А как можно сделать 2 replace подряд?

**Comment by woxcab** [comment]
Пример замены № на # и russian на RF:
`http://rssfeeder.96.lt/rss_editor-master/index.php?url=https%3A%2F%2Fzapier.com%2Fengine%2frss%2f1176719%2fplane34%2f&replace_from[]=№&replace_to[]=%23&replace_in[]=description&replace_from[]=russian&replace_to[]=RF&replace_in[]=description`

Замечание: для замены на пустую строку достаточно передать пустым replace_to (т.е. не указывать его значения), например:
`http://rssfeeder.96.lt/rss_editor-master/index.php?url=https%3A%2F%2Fzapier.com%2Fengine%2frss%2f1176719%2fplane34%2f&replace_from[]=№&replace_to[]&replace_in[]=description&replace_from[]=russian&replace_to[]=RF&replace_in[]=description`
